### ISSUE TITLE
css is not appended if there's no <head> tag

### ISSUE THREAD

**Issue by xuchaoying** [svrxjs/svrx#112]
**Describe the bug**
css is not appended if there's no `<head>` tag on the page

**Expected behavior**
Should check `<head>` tag before append css.

**Screenshots**
![image](https://user-images.githubusercontent.com/8073251/66462344-78e49980-eaad-11e9-9272-96530c78bab0.png)

**Comment by leeluolee** [comment]
And js is not appended if there's no <body> tag
