### ISSUE TITLE
运行svrx -p时，会修改项目的package.json，插件会被注入到deps

### ISSUE THREAD

**Issue by lighte-chen** [svrxjs/svrx#125]
**Describe the bug**
运行svrx -p时，会修改项目的package.json，插件会被注入到deps

**To Reproduce**
1. 在项目根目录下运行svrx -p eruda
2. 查看package.json，deps中出现svrx-plugin-eruda

**Expected behavior**
期望不会修改到package.json，因为就本地开发用

**Comment by xuchaoying** [comment]
Sorry for the bug, will fix it very soon!

**Comment by vczhan** [comment]
很多插件都很常用/通用，希望能增加全局安装的方式

**Comment by xuchaoying** [comment]
@vczhan 全局配置其实可以写到`/${HOME}/.svrx/config/.svrxrc.js` 中，格式和[工程中使用配置文件](https://docs.svrx.io/zh/plugin/usage.html#%E9%80%9A%E8%BF%87svrxrcjs%E9%85%8D%E7%BD%AE)一样

不过插件安装仍然是安装到各个工程目录中的，看下这样能否满足需求？

**Comment by vczhan** [comment]
@xuchaoying 每次使用都要安装，不太方便。

**Comment by xuchaoying** [comment]
@vczhan 工程中只会在第一次运行时安装喔， 不会每次使用都安装的。 这样设计也是为了避免插件安装包混乱。

这个 issue 原本反馈的问题已经 fix 掉了， issue 即将关闭，后续欢迎在新的 issue 中讨论全局安装的问题～
