### ISSUE TITLE
win10 svrx没反映

### ISSUE THREAD

**Issue by minhail** [svrxjs/svrx#128]
**Describe the bug**
win10 cmd窗口运行svrx后没反映~，cmd也不能ctrl c中断，而且关闭还没响应了。

**Desktop (please complete the following information):**
 - OS: win10 1809

**Additional context**
![pic](https://user-images.githubusercontent.com/21355456/67352113-a89da200-f581-11e9-96da-2029b30feac4.png)

**Comment by xuchaoying** [comment]
Hi @minhail, is your Node.js version v12? We suspect it might be somehow related to the Node.js of version v12. Can you downgrade to v10 and have another try?

Hi, 请问下你的 Node.js 版本是 v12 吗？我们怀疑可能是和 node 版本有关，可以尝试切换到 v10 试试吗？

**Comment by minhail** [comment]
我的node是v10.16.3版本的~

**Comment by zhuzhensuo** [comment]
me too , it does't work in  win10。。。。cant' quit by ctrl + c， i really 无 fuck 说。。。。 fix it plz

**Comment by leeluolee** [comment]
> me too , it does't work in win10。。。。cant' quit by ctrl + c， i really 无 fuck 说。。。。 fix it plz

@zhuzhensuo will fix  in `v1.05` , release before tomorrow

**Comment by xuchaoying** [comment]
Please update @svrx/cli to 1.0.2 and then try:

```bash
svrx install
svrx
```
