### ISSUE TITLE
HTTPS true not working

### ISSUE THREAD

**Issue by jgy3183** [svrxjs/svrx#133]
**Describe the bug**
When running in https, chrome prevents access to the site

**To Reproduce**
serve svrx with https as true

**Expected behavior**
A way to configure svrx to serve with a cert that I can manually trust on my local machine

**Desktop (please complete the following information):**
 - OS: macosx
 - Node: v12.13.0
 - Browser: chrome

**Additional context**
Not sure if this is part of the tool, but was just playing around with it and noticed that if I choose https to true, I wont be able to load the site as expected.  Also, now since most browsers require a https for access to webcam/audio/etc, it would be great to point my keychain to a cert file that I can always trust (for local development)

**Comment by leeluolee** [comment]
We want to confirm that have you got the following information 

![image](https://user-images.githubusercontent.com/731333/67537533-60f85100-f70e-11e9-80e9-e0e0b62166b0.png)

And the page should still be successfully opened after trusting the certificate?
