### ISSUE TITLE
无法启动工程

### ISSUE THREAD

**Issue by helloMr** [svrxjs/svrx#140]
**Describe the bug**
安装后，进入静态资源目录，无法启动工程
win10、x64

**To Reproduce**
1.  'npm install -g @svrx/cli'
+ @svrx/cli@1.0.3
added 48 packages from 38 contributors, removed 596 packages and updated 155 pac      kages in 28.196s

2.  'svrx --version'
- [svrx] Installing svrx core package...
[error] Error: Cannot read property 'reverse' of null

3.  'svrx'
- [svrx] Installing svrx core package...
[error] Error: Cannot read property 'reverse' of null

**Expected behavior**
启动静态服务

**Screenshots**
![image](https://user-images.githubusercontent.com/5511549/67743987-40583000-fa5b-11e9-82c9-e4f951d26d48.png)

**Desktop (please complete the following information):**
 - OS: [win10]
 - Node: [v12.10.0]
 - Browser: [chrome]
 - Version: [@svrx/cli@1.0.3]

**Comment by int64ago** [comment]
Known issue https://github.com/svrxjs/svrx/issues/128

and fixed via `1.0.4`

Please upgrade CLI: `npm i @svrx/cli@latest -g`

**Comment by int64ago** [comment]
Maybe not the same problem, feel free to reopen if still fail :-)
