### ISSUE TITLE
svrx.close() callback called slowly

### ISSUE THREAD

**Issue by imyzf** [svrxjs/svrx#141]
**Describe the bug**
1. The callback of `svrx.close()` called after a long time when svrx is closed.
2. Also, the process won't exit after close.

**To Reproduce**
```js
const svrx = require('@svrx/svrx');

const server = new svrx()
server.start().then(() => {
    console.log('-----------started-----------');
    setTimeout(() => {
        console.time('svrx')
        server.close().then(() => {
            console.log('-----------stopped-----------');
            console.timeEnd('svrx')
        })
    }, 3000);
});
```

**Expected behavior**
called as quick as possible

**Screenshots**

![image](https://user-images.githubusercontent.com/8298849/67854857-22b6c380-fb4c-11e9-9ab8-eded4f4a4a6c.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Node: v11.6.0

**Additional context**
I added `open: false` with no browser window opening, it can be closed immediately.

**Comment by xuchaoying** [comment]
Have a try with

```js
const svrx = require('@svrx/svrx');
const server = svrx()
```

![image](https://user-images.githubusercontent.com/8073251/71654438-c7cc6300-2d6c-11ea-8dfc-ef0312aa4470.png)
