### ISSUE TITLE
svrx.js unable to find static files to serve in #{webDir}

### ISSUE THREAD

**Issue by KableShow** [svrxjs/svrx#142]
##**Describe the bug**
can not use wenire plugin in my vue project.

**To Reproduce**
1. create ***webpack.config.js***
```javascript
module.exports = require('./node_modules/@vue/cli-service/webpack.config.js')
```
2. run svrx --open=external --webpack --weinre
3. error

**Screenshots**
![11](https://user-images.githubusercontent.com/8595597/67926023-e2a91c80-fbef-11e9-8b33-ab051d6e4f5c.jpg)

**Desktop (please complete the following information):**
 - OS: win 7
 - Node: 8.9.2

**Comment by int64ago** [comment]
Please run `svrx -v` and paste information here

**Comment by int64ago** [comment]
Hi, we can't reproduce in our environment, please try put the file named `test.js`:

```js
const path = require('path');
const utils = require('./utils');

getStaticWebDir = function() {
  var webDir;
  webDir = path.normalize(path.join(__dirname, '../web'));
  if (utils.fileExistsSync(webDir)) {
    return webDir;
  }
  return utils.exit('unable to find static files to serve in #{webDir}; did you do a build?');
};

console.log(getStaticWebDir());
```

into `node_modules\svrx-plugin-weinre\weinre\lib\test.js`

and run `node node_modules\svrx-plugin-weinre\weinre\lib\test.js` and tell us what happend

PS: the following is our environment

![image](https://user-images.githubusercontent.com/2230882/67946273-f66a7800-fc1b-11e9-8a98-e0b908116549.png)

**Comment by KableShow** [comment]
ok。
![image](https://user-images.githubusercontent.com/8595597/68097719-96adee80-fef3-11e9-8e89-7fa024348b60.png)
