### ISSUE TITLE
mock数据配置路由项运行时出现报错

### ISSUE THREAD

**Issue by SuperRonin** [svrxjs/svrx#144]
**Describe the bug**
运行环境在项目根目录下，router.js也在跟目录下，此时运行svrx --route router.js出现以下报错.

**To Reproduce**
1. router.js文件内容为‘get('/blog').to.json({ title: 'svrx' }); ’
2. 运行svrx --route router.js命令

**Expected behavior**
正常运行，能访问到router.js中的路由。

**Screenshots**
![image](https://user-images.githubusercontent.com/22882883/67998915-1db15b80-fc95-11e9-858c-7c1d6106ffde.png)

**版本号:**
 CLI version: 1.0.4
Svrx version: 1.0.5

**Comment by int64ago** [comment]
Hi, thanks for report, here we fixed via https://github.com/svrxjs/svrx/pull/145

We will publish a new version ASAP :-)

**Comment by int64ago** [comment]
Fixed

```
svrx install 1.0.6
```
