### ISSUE TITLE
Cannot find module '@svrx/util'

### ISSUE THREAD

**Issue by zwmmm** [svrxjs/svrx#147]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Node: [e.g. 10.0.0, 12.0.0]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
![image](https://user-images.githubusercontent.com/30194521/68004539-de8f0480-fcac-11e9-9b63-9257629ce29f.png)

**Comment by xuchaoying** [comment]
To help us locate the bug, could you please complete the `Desktop` part listed in the issue?

And we might also need the output of command `svrx -v`

**Comment by ialmost** [comment]
the same issue
svrx -v
CLI version: 1.0.4
Svrx version: 1.0.7

**Comment by xuchaoying** [comment]
Could you try remove the `node_modules` directory and reinstall dependencies,
then run svrx, see what happens. @ialmost 

I think this might relate to the same bug in #150

**Comment by ialmost** [comment]
> Could you try remove the `node_modules` directory and reinstall dependencies,
> then run svrx, see what happens. @ialmost
> 
> I think this might relate to the same bug in #150

I think so too

**Comment by xuchaoying** [comment]
And the problem is caused by https://github.com/svrxjs/svrx/issues/150#issuecomment-552264421

**Comment by xuchaoying** [comment]
fixed in 1.1.0
