### ISSUE TITLE
Error: Cannot find module 'global-npm'

### ISSUE THREAD

**Issue by ialmost** [svrxjs/svrx#150]
**Describe the bug**
plugins.mock 不支持 mock 的 Random.dataImage，于是安装 mockjs，并在 route.js 中 require 进来使用 mock.random 工具类，报 Error: Cannot find module 'global-npm'

**To Reproduce**
1. npm i mockjs -S
2. let Mock = require('mockjs'); let Random = Mock.Random; 'image': Random.dataImage('200x100')
3. svrx --webpack
4. See Error: Cannot find module 'global-npm'

**Expected behavior**
plugins.mock 不支持 mock 的 Random.dataImage，于是安装 mockjs，并在 route.js 中 require 进来使用 mock.random 工具类，报 Error: Cannot find module 'global-npm'

**-------------------------------------- 新发现分割线 --------------------------------------**

经过再一次验证，发现并非由之前的描述而引发，经过再次确认，通过以下方式可以100%复现

只要使用过  svrx --webpack 这个神奇的命令
之后不管使用 npm 安装任何 node_module，都会出现下图中那一堆的 removing，也是由此导致的问题，只能通过删除项目的 node_modules 修复该问题

另外，左侧那一堆以  _ 开头的 node_module 是什么？只要执行 svrx --webpack 就会被写入

**Screenshots**
![2](https://user-images.githubusercontent.com/6847189/68480265-5c37af00-026f-11ea-83be-4e7a0765ae5a.png)
![1](https://user-images.githubusercontent.com/6847189/68480271-5e017280-026f-11ea-845b-4ae2c840029c.png)

**Desktop (please complete the following information):**
 - Mac: 10.14.6
 - Node: 10.16.0
 - Svrx: CLI version: 1.0.4，Svrx version: 1.0.7

**Additional context**

**Comment by xuchaoying** [comment]
出现这个问题的根本原因是 `npm install` 命令会自动移除 `node_modules` 依赖中没有声明在 `package.json` 里的冗余包。在这里如果你在安装 svrx 插件后执行了 `npm install` 命令安装其它包，就会导致 svrx 插件的依赖被移除，进而导致插件不可用。

这个问题我们会在下一个 svrx 版本中修复，感谢反馈

> 另外，左侧那一堆以 _ 开头的 node_module 是什么？只要执行 svrx --webpack 就会被写入

svrx 插件是通过 [npminstall](https://github.com/cnpm/npminstall) 的方式装入的（它有个特殊的包安装机制，感兴趣可以了解下），因此`_`开头的文件夹都是 svrx 插件的依赖源包。

**Comment by xuchaoying** [comment]
fixed in 1.1.0
