### ISSUE TITLE
网易的郑海波 滚出来。《网易裁员，让保安把身患绝症的我赶出公司。我在网易亲身经历的噩梦！》

### ISSUE THREAD

**Issue by saibeitan** [svrxjs/svrx#155]
**Describe the bug**
最近看了网上热门的《网易裁员，让保安把身患绝症的我赶出公司。我在网易亲身经历的噩梦！》，本人非常愤怒，想到在网易遭遇的一切，我要直接开怼：

网易云音乐的前端主管-**郑海波**，以及HR，非法裁员（云音乐一直偷偷摸摸的裁），威逼利诱员工申请辞职，诋毁贬低下属的工作产出，暴力裁应届生。 这种道貌岸然，背地里毫无下线，干尽缺德事，不遵守国家法律的人，迟早有一天会得到现世报。

![MjBCIs.jpg](https://s2.ax1x.com/2019/11/25/MjBCIs.jpg)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Node: [e.g. 10.0.0, 12.0.0]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by leeluolee** [comment]
。。。。。。 你应该是  regularjs 那个黑人吧？ 搞清楚状况再来搞事  OK？

**Comment by leeluolee** [comment]
由于这次不是针对我个人了，而是在特殊舆论背景下，会影响到整个团队，我做如下澄清。

1. 我没有裁过任何应届生，云音乐研发这边向来也有应届生非极端不打C的惯例，我们团队校招新人入职一年内未有C案例（当然我不希望团队新人以此放松要求）
2. 可能对团队还算满意，三年间**我只在去年底劝退过一位同事，而且此同事入职之后所有阶段绩效都是C（你也可以跳出来说是你**，即使是你，为什么会成为接触的70多号人里中的唯一，自己想一想，我可以充分对峙）。 
3. 网易这次的事件，请关注官方进展，别来技术社区搞这些事，关注弱势群体是好态度，我们内部所有同事也都在关注，但请先确保**立场客观向善**，你们是在吃人血馒头，还是真的在解决问题。
4. 别网易有啥啥啥事情，就要我出来负责，你也太高看我了 ，很多年没在技术社区发声，去年底开始反而又有了关于我的消息，真的太谢谢你了
