### ISSUE TITLE
请问post handle时 如何通过ctx取得post body

### ISSUE THREAD

**Issue by hcwhan** [svrxjs/svrx#157]
```
post('/XXXX').to.handle((ctx) => {
    console.log('ctx', ctx.request.body);
    ctx.type = 'html';
    ctx.body = '<body>Hello World</body>';
});
```
`ctx.request.body` 为空

**Comment by leeluolee** [comment]
__临时解决方案__
```
npm i koa-bodyparser
```
由于被限制直接require，但实际上可以引用相对路径。

```js
const bodyParser = require('./node_modules/koa-bodyparser'); //relative path 

// bodyparser wrap
post('/XXXX').to.handle(bodyParser()).handle((ctx) => {
  console.log('ctx', ctx.request.body);
  ctx.type = 'html';
  ctx.body = ctx.request.body;
});
```

**长期解决方案请关注这个issue**， 因为**并非所有请求都应该默认parse body，因为考虑到代理等情况 ** ，我们需要评估下，但至少会提供一个 body-parser 插件出来, 避免上述又黑又脏的操作。比如

```js
post('/XXXX').to.bodyParser().handle(...)
```

**Comment by xuchaoying** [comment]
似乎更应该提供一个 action 供用户方便引入任意 koa middleware ：

```js
const bodyParser = require('koa-bodyparser');

post('/XXXX').to.middleware(bodyParser).handle((ctx) => {
  console.log('ctx', ctx.request.body);
  ctx.type = 'html';
  ctx.body = ctx.request.body;
});
```

**Comment by leeluolee** [comment]
@xuchaoying `handle` 貌似 就可以认为 use middleware  ，只是它前置了 流量筛选操作 比如 `get`、`post`等，理论上也很方便前置统一处理，而无需每条route都声明，比如你可以

```js
post(/(.*)).to.handle(bodyParser()); //后续所有post 操作都做bodyParser过滤
post('/XXXX').to.handle( ctx => {
  ctx.body = ctx.request.body;
});
```

**Comment by xuchaoying** [comment]
恩恩，我意思是需要处理用户等第三方middleware引入的便捷性问题，而不是直接提供bodyParser这样的action

**Comment by lyw9523132** [comment]
@leeluolee  @xuchaoying @hcwhan @gitter-badger @int64ago 
### 网易 郑海波，恶心裁员手段汇总

经历过网易的暴力裁员，手段极其恶心，下面曝光网易是怎么裁员：
1.  快到年底，绩效打c，直接影响员工的年终奖，一年加班白干。网易绩效完全是领导一言堂。
2.  联合HR在会议室贬低你的人格，把你的工作说的一文不值，一副高高在上的样子，各种莫须有的理由强迫你接受绩效c的结果，最终目的要逼你主动申请离职，不提任何赔偿。
3.  拿背调威胁员工。 HR威逼利诱，如果主动申请离职，背调往好处说，如果走最终辞退流程，背调上诋毁员工。 
4.  开始边缘化员工。 不给员工安排工作，不让接触新业务，冷处理员工，甚至连团队内的会议都不通知参加，让员工处在孤立无援的境地。
5.  当员工提出转岗要求时，又搬出公司规定绩效c无法转岗的说辞，断绝员工的合理请求。


这一切手段的最终目的，就是要恶心员工主动OA申请离职。 


每一个离职网易的员工，都带着愤恨离开。这家企业的各种无耻裁员举动，今天终于在全国曝光。


而网易云音乐的前端主管，郑海波，裁员手段恶劣，枉顾国家劳动法，就如那篇文章里的游戏主管一样，同样是个吃人不吐骨头的狗东西。

**Comment by xuchaoying** [comment]
v1.1.5 版本可以支持在 route 文件中引入 koa 中间件了。

```js
const bodyParser = require('koa-bodyparser');

post('/test/post').to.handle(bodyParser()).handle((ctx) => {
  ctx.type = 'html';
  ctx.body = ctx.request.body;
});
```
