### ISSUE TITLE
网易 郑海波，恶心裁员手段汇总

### ISSUE THREAD

**Issue by lyw9523132** [svrxjs/svrx#158]
**Describe the bug**
经历过网易的暴力裁员，手段极其恶心，下面曝光网易是怎么裁员：
1.  快到年底，绩效打c，直接影响员工的年终奖，一年加班白干。网易绩效完全是领导一言堂。
2.  联合HR在会议室贬低你的人格，把你的工作说的一文不值，一副高高在上的样子，各种莫须有的理由强迫你接受绩效c的结果，最终目的要逼你主动申请离职，不提任何赔偿。
3.  拿背调威胁员工。 HR威逼利诱，如果主动申请离职，背调往好处说，如果走最终辞退流程，背调上诋毁员工。 
4.  开始边缘化员工。 不给员工安排工作，不让接触新业务，冷处理员工，甚至连团队内的会议都不通知参加，让员工处在孤立无援的境地。
5.  当员工提出转岗要求时，又搬出公司规定绩效c无法转岗的说辞，断绝员工的合理请求。

这一切手段的最终目的，就是要恶心员工主动OA申请离职。 

每一个离职网易的员工，都带着愤恨离开。这家企业的各种无耻裁员举动，今天终于在全国曝光。

而网易云音乐的前端主管，郑海波，裁员手段恶劣，枉顾国家劳动法，就如那篇文章里的游戏主管一样，同样是个吃人不吐骨头的狗东西。

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Node: [e.g. 10.0.0, 12.0.0]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by int64ago** [comment]
兄弟，能够感受到你的气氛，是个男人就实名曝光，躲在键盘后面拿小号叽叽歪歪让人很看不起的

**Comment by leeluolee** [comment]
https://github.com/svrxjs/svrx/issues/155#issuecomment-558056570   其他情况都在这了，清者自清。   

既然你算是明确跳出来了，我再好好回复你一下吧，这些帖子我让他们先不删。

- 招你是招聘事故（虽然你不是我招聘的，而是部门合并带进来的，否则根本进不了我们部门），还记得你事后一次绩效沟通承认能力有差，还希望我们降技术评级留下来，真是人才。
- 其次你**本来就下半年入职，还在试用期，2次C了**，你何来的年底裁员，一年加班白干，年终奖之说，你加过什么班？别来蹭网易游戏策划的热度，你不配！
- 从去年底你乱咬我开始，我都是正面回复你（别人都说我唐僧了），你呢？申请了多少临时账号了？   **又怂又坏**。  匿名社区有同事反馈也有人咬我，看来也是你了， 真是可悲，小人。
- 如果转岗可以，又有团队急着要，我真希望把你这大神请走。
