### ISSUE TITLE
Cannot read property '_getScopedInstance' of undefined

### ISSUE THREAD

**Issue by TalonBoom** [svrxjs/svrx#166]
**Describe the bug**
在项目使用require.js做模块管理时，svrx启动后， 控制台报错  Cannot read property '_getScopedInstance' of undefined

**To Reproduce**

1、使用require.js 管理 各个js模块  

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Windows_NT 10.0.15063 x64
 - Node: v10.17.0
 - Browser: chrome
 - Version: 1.1.3
 
**Additional context**

**Comment by xuchaoying** [comment]
fixed in @svrx/svrx@1.1.4
