### ISSUE TITLE
livereload feature work incorrectly when using root && route options via node.js API[win10 only]

### ISSUE THREAD

**Issue by tym1193** [svrxjs/svrx#170]
**Describe the bug**
 `livereload` feature work incorrectly when using `root` && `route` options via node.js API

**To Reproduce**

1. Run `Server-X` with `root` && `route` options via `node.js` API

2. Ensure `Server-X` running correctly at port `8000` `[default port]`

3. Place a `route.js` file to `path-to-route/route.js`

    _route.js_

    `get('/test.html').to.send('<html>test from mock server</html>')`

4. Open `http://localhost:8000/test.html` in browser

  - > It will display a text of `"test from mock server"`.

5. Edit `path-to-route/route.js` and try to **save multiple times**

6. Refresh browser with the same url `http://localhost:8000/test.html` while trying `step 5`.

  - > `livereload` feature seems to be broken then display a `404 Not Found` page

**Desktop (please complete the following information):**

 - OS: windows 10
 - Node: 8.16.0
 - Browser: chrome/firefox
 - Version: 1.1.3

bug recurrence project: [github link](https://github.com/tym1193/svrx-bug-recurrence)

**Comment by xuchaoying** [comment]
Seems cannot reproduce here on my computer :cry: 

```
OS: windows 10
Node: 8.16.0
Version: 1.1.3
```

So what do you edit in step 5 ?

Does the terminal print any logs after you save the `route.js`?

**Comment by tym1193** [comment]
> Seems cannot reproduce here on my computer 😢
> 
> ```
> OS: windows 10
> Node: 8.16.0
> Version: 1.1.3
> ```
> 
> So what do you edit in step 5 ?
> 
> Does the terminal print any logs after you save the `route.js`?

Just save without editing.
outputs:
`[svrx] [routing update] D:\xxx\config\route.js`

Cannot reproduce on other computers😢
