### ISSUE TITLE
cors 默认开启但是没有效果

### ISSUE THREAD

**Issue by yorkfread** [svrxjs/svrx#172]
mock 的请求中没有携带 cors 的请求头，导致跨域问题

route.js
`get('/news').to.mock({
    'code': 200 })`

![image](https://user-images.githubusercontent.com/26402739/71312834-eed08e00-246a-11ea-8393-be2a4ede910f.png)

**Comment by int64ago** [comment]
请问你完整使用方式是什么？如果是 `svrx` 直接启的话是在一个域才对，为什么会出现跨域问题？

**Comment by yorkfread** [comment]
> 请问你完整使用方式是什么？如果是直接`svrx`启的话是在一个域才对，为什么会出现跨域问题？

不好意思，经你这么一提醒才发现是我的使用方式有误，现我在项目根目录中使用`svrx --webpack`启动已解决问题

复述一下之前我的使用方式：
在项目的目录中新建了个文件夹，放置 svrx 的配置文件，并直接用命令`svrx`启动
用 vue ui 的方式运行项目，此时两个服务的端口不一样，所以导致了跨域

另外提一下：
如果我确实想独立启动一个`svrx`的服务，主要用于 mock 数据，是否可以支持跨域呢？
web 页面用另外一个服务启动，比如使用[flask](https://github.com/pallets/flask)

**Comment by int64ago** [comment]
> 如果我确实想独立启动一个svrx的服务，主要用于 mock 数据，是否可以支持跨域呢

那这个主次可能搞错了，svrx 主要是提供 dev server，mock 只是一个扩展，如果你仅仅单纯需要 mock server 其实有更多更好的选择

**Comment by yorkfread** [comment]
> 那这个主次可能搞错了，svrx 主要是提供 dev server，mock 只是一个扩展，如果你仅仅单纯需要 mock server 其实有更多更好的选择

好的，经你这么一说是我搞错了`svrx`的核心，我主要是需要 mock 跟 proxy 的能力，方便接口调试

>如果是这样，应该是 Flask 服务提供跨域支持才对

是 Flask 既做前端也做后端接口，Flask 的前端页面需要使用`svrx`来提供接口数据，应该是`svrx`来增加 CORS 头，不过可能这脱离了`svrx`的核心，毕竟主要是做 dev server

**Comment by leeluolee** [comment]
@yorkfread 这个应该是`svrx`的一个Bug，  你的用法没问题的，本来就属于一种使用姿势。 不过如果可能的话，其实更推荐使用svrx直接启动的方式。  下个版本我们修复吧 :)

**Comment by xuchaoying** [comment]
fixed in @svrx/svrx@1.1.4
