### ISSUE TITLE
svrx起的socket进程在开发过程中经常会失败

### ISSUE THREAD

**Issue by cuixi** [svrxjs/svrx#180]
**Describe the bug**
小程序开发起的socket进程在开发过程中经常会失败，导致live reload无法正常工作，也无法手动刷新，需要重新run启动程序

**Screenshots**
![socket](https://user-images.githubusercontent.com/8605867/75942077-6fc8ee80-5ecc-11ea-8d3c-56bc751e6c38.jpg)

**Desktop (please complete the following information):**

 - OS: macOS 10.14.6
 - Node: v11.0.0
 - Browser: chrome 80.0.3987.132
 - Version: ^1.1.4
 
**Additional context**
本地连接了easyconnect vpn，不知道是不是有影响

**Comment by xuchaoying** [comment]
需要提供更具体的问题复现描述，还有问题可以随时 reopen
