### ISSUE TITLE
是否有支持开启SSI的配置或插件

### ISSUE THREAD

**Issue by coldShan** [svrxjs/svrx#184]
**Is your feature request related to a problem? Please describe.**
本地开发需要使用到SSI功能，之前是使用nginx来开启SSI。需要这个配置是因为有些项目是多个html文件，但有相同的资源引入或页面有侧边栏等公用组件。创建自定义组件的实现的话，比如侧边栏，每个页面都要生成一次，切换页面的时候会出现页面白屏闪烁，SSI可以实现类似于单页面应用的流畅切换效果。部分项目无法作为单页面应用开发，所以需要这个配置。

**Describe the solution you'd like**
希望有相关的配置或者插件能实现此功能。

**Describe alternatives you've considered**

**Additional context**

谢谢。

**Comment by leeluolee** [comment]
你好， @coldShan  是类似Nginx的SSI 吗？大概在什么场景使用？ 另外请尽可能按我们的Issue模板提交哈，帮助我们改进或修复问题

**Comment by coldShan** [comment]
@leeluolee 谢谢回复。之前是用nginx开启SSI。issue已经按模板修改过了。

**Comment by leeluolee** [comment]
@coldShan 初步看可以安排上

**Comment by coldShan** [comment]
@leeluolee 好的，谢谢~

**Comment by leeluolee** [comment]
### 思路如下


静态html 或 服务端返回响应为html 类型， 解析html其中的占位标记， 标记语法和Nginx SSI 一致

```
<html>
    <head>
    </head>
    <body>
    	A.OK
        <!--引入b.html-->
        <!--# include file="b.html" -->
    </body>
</html>
```
加载对应路由下的内容进行注入


#### 激活方式

```js
svrx --ssi
```

or 需要参数

```js
svrx -p ssi?length=256
```

@coldShan 合理并满足你需求么？

**Comment by coldShan** [comment]
@leeluolee 嗯，就是这样，非常感谢。

**Comment by leeluolee** [comment]
`svrx --ssi`  @coldShan  可以尝试下看看，目前只支持 file  不支持  virtual

插件地址：https://github.com/svrxjs/svrx-plugin-ssi

**Comment by coldShan** [comment]
@leeluolee 辛苦☕️，试过了，可以正常使用，配置方法也很简单，谢谢。

**Comment by leeluolee** [comment]
需求已支持
