### ISSUE TITLE
希望官方开发默认支持less的插件

### ISSUE THREAD

**Issue by zenonux** [svrxjs/svrx#187]
**Is your feature request related to a problem? Please describe.**
发现用来写老的，轻量级jquery项目挺舒服的，但是不支持less， 需要另开一个终端编译less，es6转es5同

**Describe the solution you'd like**
如果官方开发的插件里面默认支持less编译就好了

**Comment by xuchaoying** [comment]
如果你感兴趣的话，不如尝试贡献一个 `less` 插件～ :D  

[如何写一个插件](https://docs.svrx.io/zh/plugin/contribution.html)

**Comment by leeluolee** [comment]
@zenonux 其实如果已经需要引入多个构建流程，建议直接引入 webpack， 并使用[svrx-plugin-webpack](https://github.com/svrxjs/svrx-plugin-webpack)  串起来（不过这个依赖本身你对webpack的使用）， 你可以尝试下，如果不行，我可以给你个例子

**Comment by zenonux** [comment]
> @zenonux 其实如果已经需要引入多个构建流程，建议直接引入 webpack， 并使用[svrx-plugin-webpack](https://github.com/svrxjs/svrx-plugin-webpack) 串起来（不过这个依赖本身你对webpack的使用）， 你可以尝试下，如果不行，我可以给你个例子

其实我就用来写个jquery多页面的小项目，livereload,route proxy,这两个就基本满足了。开箱即用，项目目录下也没有node_modules ，比较干净。现在好像有个ssi多了模版的功能又方便了点。 所以对于我的需求就是less,es6的问题了。gulp webpack都要配置麻烦。目前用了一个koala解决这个问题。主要是开箱即用，不用配置什么东西，多个项目也不用复制来复制去

**Comment by zenonux** [comment]
> 如果你感兴趣的话，不如尝试贡献一个 `less` 插件～ :D
> 
> [如何写一个插件](https://docs.svrx.io/zh/plugin/contribution.html)

有空再研究一下吧😄

**Comment by cooliean** [comment]
希望官方开发默认支持Sass的插件 ：）））

**Comment by zenonux** [comment]
> 希望官方开发默认支持Sass的插件 ：）））

大兄弟，跟我一样自己搞吧
