### ISSUE TITLE
用了charles的远程映射,把本地代码替换线上代码,这个时候svrx启动的一切插件都会失效

### ISSUE THREAD

**Issue by XiaoLizi29** [svrxjs/svrx#189]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

 - Node: [e.g. 10.0.0, 12.0.0]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 
**Additional context**

**Comment by leeluolee** [comment]
#193  duplicate
