### ISSUE TITLE
svrx在真机的外部浏览器运行正常,在微信内部浏览器所有插件就都失效了

### ISSUE THREAD

**Issue by XiaoLizi29** [svrxjs/svrx#192]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

 - Node: [e.g. 10.0.0, 12.0.0]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 
**Additional context**

**Comment by leeluolee** [comment]
在 #193 处理
