### ISSUE TITLE
Error: Circular symlink detected

### ISSUE THREAD

**Issue by xdliyushen** [svrxjs/svrx#205]
**Describe the bug**
在 mac 根目录下执行 `svrx` 命令，十几秒钟后服务宕机。

**To Reproduce**
1. cd ~
2. svrx 

**Expected behavior**
服务器正常工作

**Screenshots**
![截屏2021-05-31 下午3 59 56](https://user-images.githubusercontent.com/37898499/120160874-53c81000-c229-11eb-81c3-ab09cb7260d0.png)

**Desktop (please complete the following information):**

- CLI version: 1.1.4
- Svrx version: 1.1.7
- Node version: v14.8.0
- OS version: Darwin 19.6.0 x64

**Comment by dayjoyx** [comment]
额，如果要在根目录做文件浏览有一个办法 

```
svrx --no-livereload
```

**Comment by xdliyushen** [comment]
现在可以正常工作啦，多谢
