### ISSUE TITLE
Wrong version installed

### ISSUE THREAD

**Issue by int64ago** [svrxjs/svrx#87]
**Describe the bug**

It's a fresh installation, but installed wrong svrx version `3.3.7`

**To Reproduce**
1. `npm i svrx-cli -g`
2. `svrx -h`
3. `svrx ls`

**Expected behavior**

Install the latest version `0.0.9`

**Screenshots**

![photo_2019-09-09_00-41-37](https://user-images.githubusercontent.com/2230882/64497713-e9e43600-d2e2-11e9-9629-f2ec8e594d56.jpg)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 x86_64
 - Node: v10 LTS

**Comment by xuchaoying** [comment]
Will be fixed after #83 merged
